server:
  servlet:
    context-path: /fiap-gestao
  port: 8090
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiap
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      schema: webservice
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: webservice
